//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.HackMCR.Website {
    
    
    public partial class Meetings {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MMP.HackMCR.Website.Layout Master {
            get {
                return ((MMP.HackMCR.Website.Layout)(base.Master));
            }
        }
    }
}
